#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

mapfile -d '' files < <(git diff --cached --name-only --diff-filter=ACMR -z -- '*.nix')
((${#files[@]} == 0)) && exit 0

nixfmt "${files[@]}"
git add -- "${files[@]}"
