{ ... }:
{
  homeManager.modules.desktop =
    {
      config,
      pkgs,
      ...
    }:
    let
      wallpaper_path = "/home/lucid/dotfiles/media/wallpapers/wallpaper.jpg";
    in
    {
      ############################################
      # HYPRPAPER
      ############################################
      services.hyprpaper.enable = true;

      # Generate hyprpaper.conf directly (v0.8.4 uses block syntax)
      xdg.configFile."hypr/hyprpaper.conf" = {
        text = ''
          ipc=on
          splash=false
          preload=${wallpaper_path}
          wallpaper {
            monitor=
            path=${wallpaper_path}
            fit_mode=cover
          }
        '';
      };

      ############################################
      # HYPRLAND SESSION HELPERS
      ############################################
      xdg.configFile."hypr/hyprland.conf".text = ''
        # Managed by Home Manager. Hyprland 0.55+ uses hyprland.lua.
      '';

      xdg.configFile."hypr/hyprland.lua".text = ''
        local terminal = "ghostty"
        local fileManager = "nemo"
        local menu = 'rofi -show drun -modi "drun,run,window,system:${config.home.homeDirectory}/.config/hypr/scripts/rofi-system.sh"'
        local mainMod = "SUPER"

        -- Monitor layout is generated by nwg-displays; fallback keeps current geometry exactly.
        if not pcall(require, "monitors") then
          hl.monitor({ output = "eDP-1", mode = "3456x2160@60.0", position = "1021x1080", scale = 1.8 })
          hl.monitor({ output = "DP-2", mode = "1920x1080@60.0", position = "1021x0", scale = 1.0 })
        end

        local function read(path)
          local file = io.open(path, "r")
          if not file then return "" end
          local text = file:read("*a")
          file:close()
          return text
        end

        local function rgba(text, name, fallback)
          return text:match("%$" .. name .. "%s*=%s*(rgba%([^)]+%))") or fallback
        end

        local function apply_wallust()
          local text = read(os.getenv("HOME") .. "/.config/hypr/wallust-colors.conf")
          local bg = rgba(text, "wallust_bg", "rgba(1a1a1aee)")
          local accent = rgba(text, "wallust_accent", "rgba(33ccffee)")
          local accent2 = rgba(text, "wallust_accent2", "rgba(00ff99ee)")
          local inactive = text:match("col%.inactive_border%s*=%s*(rgba%([^)]+%))") or "rgba(595959aa)"

          hl.config({
            general = {
              col = {
                active_border = { colors = { accent, accent2 }, angle = 45 },
                inactive_border = inactive,
              },
            },
            decoration = { shadow = { color = bg } },
          })
        end

        hl.config({
          general = {
            gaps_in = 6,
            gaps_out = 18,
            border_size = 2,
            col = {
              active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
              inactive_border = "rgba(595959aa)",
            },
            resize_on_border = true,
            allow_tearing = false,
            layout = "dwindle",
          },
          decoration = {
            rounding = 8,
            rounding_power = 2,
            active_opacity = 1.0,
            inactive_opacity = 0.94,
            shadow = {
              enabled = true,
              range = 10,
              render_power = 3,
              color = "rgba(1a1a1aee)",
            },
            blur = {
              enabled = true,
              size = 6,
              passes = 2,
              vibrancy = 0.12,
            },
          },
          animations = { enabled = true },
          dwindle = { preserve_split = true },
          master = { new_status = "master" },
          misc = {
            force_default_wallpaper = 0,
            disable_hyprland_logo = true,
          },
          input = {
            kb_layout = "us",
            kb_variant = "",
            kb_model = "",
            kb_options = "",
            kb_rules = "",
            follow_mouse = 1,
            sensitivity = 0,
            touchpad = { natural_scroll = true },
          },
          xwayland = { force_zero_scaling = true },
        })

        apply_wallust()

        hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
        hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
        hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
        hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
        hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

        hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
        hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
        hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
        hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 94%" })
        hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.8, bezier = "quick", style = "popin 94%" })
        hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
        hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
        hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
        hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
        hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
        hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
        hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
        hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
        hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
        hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
        hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

        hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
        hl.device({ name = "epic-mouse-v1", sensitivity = -0.5 })

        -- UWSM owns the graphical session lifecycle; session services are
        -- declarative Home Manager units rather than compositor child processes.
        hl.on("hyprland.start", function()
          hl.exec_cmd("~/.config/hypr/scripts/wallust-apply.sh")
        end)

        hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
        hl.bind(mainMod .. " + C", hl.dsp.window.close())
        hl.bind(mainMod .. " + M", hl.dsp.exit())
        hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
        hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
        hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
        hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
        hl.bind(mainMod .. " + T", hl.dsp.layout("togglesplit"))

        hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
        hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
        hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
        hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
        hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
        hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
        hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
        hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))

        for i = 1, 10 do
          local key = i % 10
          hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
          hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
        end

        hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
        hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
        hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
        hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
        hl.bind(mainMod .. " + mouse:272", function()
          hl.dispatch(hl.dsp.window.drag())
          hl.exec_cmd("canvas-ctl edge-start")
        end, { mouse = true })
        hl.bind(mainMod .. " + mouse:272", hl.dsp.exec_cmd("canvas-ctl edge-stop"), { mouse = true, release = true })
        hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

        hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
        hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
        hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
        hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
        hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
        hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
        hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
        hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
        hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
        hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

        hl.bind(mainMod .. " + SHIFT + mouse:272", hl.dsp.exec_cmd("canvas-ctl pan-start"), { mouse = true })
        hl.bind(mainMod .. " + SHIFT + mouse:272", hl.dsp.exec_cmd("canvas-ctl pan-stop"), { mouse = true, release = true })
        hl.bind(mainMod .. " + SHIFT + left", hl.dsp.exec_cmd("canvas-ctl nav-left"))
        hl.bind(mainMod .. " + SHIFT + right", hl.dsp.exec_cmd("canvas-ctl nav-right"))
        hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("canvas-ctl canvas-toggle"))
        hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("canvas-ctl toggle"))

        hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd('cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy'))
        hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp)" - | swappy -f -'))
        hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grim - | swappy -f -"))

        hl.bind(mainMod .. " + comma", hl.dsp.focus({ workspace = "e-1" }))
        hl.bind(mainMod .. " + period", hl.dsp.focus({ workspace = "e+1" }))
        hl.bind(mainMod .. " + SHIFT + comma", hl.dsp.window.move({ workspace = "e-1" }))
        hl.bind(mainMod .. " + SHIFT + period", hl.dsp.window.move({ workspace = "e+1" }))

        hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
        hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))
        hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
        hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))

        hl.bind(mainMod .. " + B", hl.dsp.submap("resize"))
        hl.define_submap("resize", function()
          hl.bind("h", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })
          hl.bind("j", hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })
          hl.bind("k", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
          hl.bind("l", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })
          hl.bind("escape", hl.dsp.submap("reset"))
          hl.bind("Return", hl.dsp.submap("reset"))
        end)

        hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("~/.config/hypr/scripts/cheatsheet.sh"))

        hl.window_rule({
          name = "suppress-maximize-events",
          match = { class = ".*" },
          suppress_event = "maximize",
        })

        hl.window_rule({
          name = "fix-xwayland-drags",
          match = {
            class = "^$",
            title = "^$",
            xwayland = true,
            float = true,
            fullscreen = false,
            pin = false,
          },
          no_focus = true,
        })
      '';

      # Rofi system mode script (switched via Ctrl+Tab inside rofi)
      home.file = {
        ".config/hypr/scripts/wallust-apply.sh" = {
          text = ''
            #!/usr/bin/env bash
            set -euo pipefail
            wallpaper="${wallpaper_path}"
            wallust -d /home/lucid/dotfiles/wallust run "$wallpaper"
            hyprctl hyprpaper wallpaper ",$wallpaper" 2>/dev/null || true
            pkill -SIGUSR2 -x .waybar-wrapped 2>/dev/null || pkill -SIGUSR2 -x waybar 2>/dev/null || true
            swaync-client -rs 2>/dev/null || true
            hyprctl reload 2>/dev/null || true
          '';
          executable = true;
        };

        ".local/bin/set-wallpaper" = {
          text = ''
            #!/usr/bin/env bash
            set -euo pipefail
            if [ "$#" -ne 1 ]; then
              echo "usage: set-wallpaper /path/to/image" >&2
              exit 2
            fi
            install -m 0644 "$1" ${wallpaper_path}
            ~/.config/hypr/scripts/wallust-apply.sh
          '';
          executable = true;
        };

        ".config/hypr/scripts/rofi-system.sh" = {
          text = ''
            #!/usr/bin/env bash
            if [ -n "$1" ]; then
              case "$1" in
                "Bluetooth Settings") blueman-manager ;;
                "Bluetooth Quick Connect") pkill -x rofi 2>/dev/null; (rofi-bluetooth) & ;;
                "Network Settings") nm-connection-editor ;;
                "WiFi Quick Connect") pkill -x rofi 2>/dev/null; (networkmanager_dmenu) & ;;
                "Audio") pavucontrol ;;
                "Monitors") nwg-displays ;;
                "Screenshot (area)") pkill -x rofi 2>/dev/null; (grim -g "$(slurp)" - | swappy -f -) & ;;
                "Screenshot (full)") pkill -x rofi 2>/dev/null; (grim - | swappy -f -) & ;;
                "Lock Screen") hyprlock ;;
                "Clipboard") pkill -x rofi 2>/dev/null; (cliphist list | rofi -dmenu -p Clipboard | cliphist decode | wl-copy) & ;;
                "Do Not Disturb") swaync-client -d ;;
                "Sleep") systemctl suspend ;;
                "Reboot") systemctl reboot ;;
                "Shutdown") systemctl poweroff ;;
                "Logout") hyprctl dispatch exit ;;
              esac
            else
              printf '%s\n' \
                "Bluetooth Settings" \
                "Bluetooth Quick Connect" \
                "Network Settings" \
                "WiFi Quick Connect" \
                "Audio" \
                "Monitors" \
                "Screenshot (area)" \
                "Screenshot (full)" \
                "Lock Screen" \
                "Clipboard" \
                "Do Not Disturb" \
                "Sleep" \
                "Reboot" \
                "Shutdown" \
                "Logout"
            fi
          '';
          executable = true;
        };

        ".config/hypr/scripts/caffinate.sh" = {
          text = ''
            #!/usr/bin/env bash
            if systemctl --user is-active hypridle &>/dev/null; then
              systemctl --user stop hypridle
              notify-send "☕ Caffinate ON" "System will not lock or sleep"
            else
              systemctl --user start hypridle
              notify-send "☕ Caffinate OFF" "Normal idle behavior restored"
            fi
          '';
          executable = true;
        };

        ".config/hypr/scripts/cheatsheet.sh" = {
          text = ''
            #!/usr/bin/env bash
            notify-send -t 20000 "Hyprland Keybinds" "$(cat ~/.config/hypr/keybinds.txt)"
          '';
          executable = true;
        };

        ".config/hypr/hyprlock.conf".text = ''
          source = ~/.config/hypr/wallust-hyprlock.conf

          background {
            monitor =
            path = ${wallpaper_path}
            blur_passes = 3
            blur_size = 8
            vibrancy = 0.12
          }

          input-field {
            monitor =
            size = 320, 56
            outline_thickness = 2
            rounding = 8
            dots_size = 0.18
            dots_spacing = 0.32
            outer_color = $wallust_accent
            inner_color = $wallust_bg_clear
            font_color = $wallust_fg
            fade_on_empty = false
            placeholder_text = <span>    password</span>
            fail_text = <span>  authentication failed</span>
            fail_color = $wallust_fail
            position = 0, -70
            halign = center
            valign = center
          }

          label {
            monitor =
            text = cmd[update:1000] date +"%H:%M"
            color = $wallust_fg
            font_size = 72
            font_family = JetBrains Mono Nerd Font
            position = 0, 120
            halign = center
            valign = center
          }

          label {
            monitor =
            text = cmd[update:60000] date +"%A  ·  %d %B"
            color = $wallust_accent
            font_size = 16
            font_family = JetBrains Mono Nerd Font
            position = 0, 48
            halign = center
            valign = center
          }

          label {
            monitor =
            text =   Arthur
            color = $wallust_fg
            font_size = 14
            font_family = JetBrains Mono Nerd Font
            position = 0, -135
            halign = center
            valign = center
          }

          label {
            monitor =
            text = cmd[update:5000] sh -c 'printf "󰁹  %s%%" "$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null || echo --)"'
            color = $wallust_fg
            font_size = 14
            font_family = JetBrains Mono Nerd Font
            position = -28, -24
            halign = right
            valign = top
          }
        '';

        ".config/hypr/keybinds.txt".text = ''
          HYPRLAND KEYBINDS (Corne 40%)
          ==============================

          FOCUS:
            Super + h/j/k/l        focus left/down/up/right

          WORKSPACES:
            Super + ,              previous workspace
            Super + .              next workspace
            Super Shift + ,        move window to prev workspace
            Super Shift + .        move window to next workspace

          WINDOW OPS:
            Super Shift + h/j/k/l  move window in direction
            Super + B              resize mode (hjkl to resize, ESC/Enter to exit)
            Super + T              toggle split layout
            Super + V              toggle floating
            Super + C              close window

          LAUNCH:
            Super + Q    terminal        Super + E    file manager
            Super + R    rofi launch     Super + S    scratchpad
            Super + /    show this cheatsheet

          CANVAS:
            Super Shift + LMB        pan canvas
            Super Shift + Left/Right  navigate to prev/next window
            Super Shift + C           toggle canvas floating mode
            Super Shift + G           invert pan direction

          SYSTEM:
            Super + M    exit Hyprland

        '';
      };

      systemd.user.services.waybar = {
        Unit = {
          Description = "Waybar status bar";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = "${pkgs.waybar}/bin/waybar";
          ExecReload = "${pkgs.coreutils}/bin/kill -SIGUSR2 $MAINPID";
          Restart = "on-failure";
        };
      };

      services.playerctld.enable = true;

      # Ghostty terminal config (wallust will add colors)
      programs.ghostty.enable = true;
      programs.hyprlock.enable = true;

      services.hypridle = {
        enable = true;
        settings = {
          general = {
            lock_cmd = "hyprlock";
            before_sleep_cmd = "hyprlock";
          };
          listener = [
            {
              timeout = 300;
              on-timeout = "hyprlock";
            }
            {
              timeout = 600;
              on-timeout = "systemctl suspend";
            }
          ];
        };
      };
    };
}
