{ ... }:
{
  homeManager.modules.common = {
    programs.tmux = {
      enable = true;
      terminal = "tmux-256color";
      historyLimit = 50000;
      keyMode = "vi";
      mouse = true;

      extraConfig = ''
        # Prefix: Ctrl+A (like screen)
        unbind C-b
        set -g prefix C-a
        bind C-a send-prefix

        # Split panes with | and -
        bind | split-window -h -c "#{pane_current_path}"
        bind - split-window -v -c "#{pane_current_path}"
        unbind '"'
        unbind %

        # Reload config
        bind r source-file ~/.tmux.conf

        # Status bar: compact blocks matching Waybar
        set -g status-position bottom
        set -g status-interval 5
        set -g status-left-length 30
        set -g status-right-length 80
        set -g status-style "bg=default,fg=#dfe9f6"
        set -g status-left "#[bg=#00000d,fg=#dfe9f6,bold]  #S  #[default]"
        set -g status-right "#[bg=#00000d,fg=#dfe9f6]   #(whoami)@#h  󰁹 #(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null || printf -- '--')%%   %I:%M %p   %a %d %b  #[default]"

        set -g window-status-separator " "
        set -g window-status-format "#[bg=#00000d,fg=#dfe9f6]  #I #W#{?window_zoomed_flag, 󰊓,}  #[default]"
        set -g window-status-current-format "#[bg=#89b4fa,fg=#00000d,bold]  #I #W#{?window_zoomed_flag, 󰊓,}  #[default]"
        set -g window-status-activity-style "bg=#00000d,fg=#89b4fa,bold"

        # Pane borders
        set -g pane-border-style "fg=#00000d"
        set -g pane-active-border-style "fg=#89b4fa"
        set -g pane-border-status off

        # Prompts and copy mode
        set -g message-style "bg=#00000d,fg=#dfe9f6"
        set -g message-command-style "bg=#89b4fa,fg=#00000d,bold"
        set -g mode-style "bg=#89b4fa,fg=#00000d,bold"

        # Enable true color
        set -ga terminal-overrides ",xterm-256color:Tc"

        # Wallust overrides, generated by `wallust run`
        if-shell 'test -f ~/.config/tmux/wallust.conf' 'source-file ~/.config/tmux/wallust.conf'
      '';
    };
  };
}
